# Generated by Django 5.0.6 on 2024-07-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_reduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reduction',
        ),
    ]
