# Generated by Django 5.0.6 on 2024-09-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_options_product_is_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bio_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
