# Generated by Django 5.0.6 on 2024-07-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('product_site', models.CharField(choices=[('LIL', 'Lille'), ('VIO', 'Violet'), ('VIA', 'Viaduc'), ('LOU', 'Lourmel')], max_length=10)),
                ('stock_DDM', models.DateField(null=True)),
                ('entry_status', models.BooleanField(default=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('modified_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_unit_price', models.IntegerField(default=0)),
                ('product_type', models.CharField(max_length=10)),
                ('on_going_command', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock.stock')),
            ],
        ),
    ]
