# Generated by Django 5.0.6 on 2024-07-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_company_name_alter_client_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('company_name',)},
        ),
    ]
