# Generated by Django 5.0.6 on 2024-07-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_item_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='reduction',
            new_name='invoice_reduction',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='reduction',
            new_name='item_reduction',
        ),
    ]
