# Generated by Django 5.0.6 on 2024-07-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_rename_reduction_invoice_invoice_reduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
