# Generated by Django 5.0.6 on 2024-07-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_item_item_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_number',
            new_name='item_num',
        ),
    ]
